// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProgettoContatti.DAL;

#nullable disable

namespace ProgettoContatti.DAL.Migrations
{
    [DbContext(typeof(RubricaContext))]
    [Migration("20240820150006_PersonaAddCittaDiNascita")]
    partial class PersonaAddCittaDiNascita
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProgettoContatti.DAL.Models.ContattoModel", b =>
                {
                    b.Property<int>("IdContatto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Pk_Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdContatto"));

                    b.Property<string>("Descrizione")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("IdPersona")
                        .HasColumnType("int")
                        .HasColumnName("Fk_Persona_Id");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.HasKey("IdContatto");

                    b.HasIndex("IdPersona");

                    b.ToTable("Contatto");
                });

            modelBuilder.Entity("ProgettoContatti.DAL.Models.PersonaModel", b =>
                {
                    b.Property<int>("IdPersona")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Pk_Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPersona"));

                    b.Property<string>("CittaDiNascita")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Cognome")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("DataDiNascita")
                        .HasColumnType("datetime2");

                    b.Property<int>("Eta")
                        .HasColumnType("int");

                    b.Property<int>("Genere")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("IdPersona");

                    b.ToTable("Persona");
                });

            modelBuilder.Entity("ProgettoContatti.DAL.Models.ContattoModel", b =>
                {
                    b.HasOne("ProgettoContatti.DAL.Models.PersonaModel", "Persona")
                        .WithMany("Contatti")
                        .HasForeignKey("IdPersona")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Persona");
                });

            modelBuilder.Entity("ProgettoContatti.DAL.Models.PersonaModel", b =>
                {
                    b.Navigation("Contatti");
                });
#pragma warning restore 612, 618
        }
    }
}
